### ISSUE TITLE
Cannot download https://mi.eng.cam.ac.uk/~nm480/woz_2.0.zip

### ISSUE THREAD

**Issue by SeekPoint** [salesforce/glad#1]

**Comment by vzhong** [comment]
Thanks for noticing this! It seems like you can also obtain the (English) data files from [here](https://github.com/nmrksic/neural-belief-tracker/tree/master/data/woz).

**Comment by vzhong** [comment]
@loveJasmine can you please try #2? I will merge this after I get a chance to verify the model performance.
