### ISSUE TITLE
RuntimeError while training: The expanded size of the tensor must match the existing size at non-singleton dimension 

### ISSUE THREAD

**Issue by Adnandev123** [salesforce/glad#10]
I am trying to run the train.py and the embedding I am using is Wikipedia embedding with 50 dimension size in python 3. I am getting this following error.

Namespace(batch_size=50, demb=400, dexp='exp', dhid=200, dout='exp/glad/default', dropout={'emb': 0.2, 'local': 0.2, 'global': 0.2}, epoch=50, gpu=0, lr=0.001, model='glad', nick='default', resume=None, seed=42, stop='joint_goal', test=False)

WARNING:root:loading split train
WARNING:root:loading split dev
WARNING:root:loading split test

INFO:root:dataset sizes: {'dev': 200, 'test': 400, 'train': 600}
INFO:root:loaded model <class 'models.glad.Model'>
INFO:root:saving config to exp/glad/default/config.json

Traceback (most recent call last):
  File "train.py", line 66, in <module>
    run(args)
  File "train.py", line 24, in run
    model.load_emb(Eword)
  File "/mount/studenten/SpokenLanguageProcessing/2019/WokeSpoke/SLU/glad_master/models/glad.py", line 151, in load_emb
    self.emb_fixed.weight.data.copy_(new(Eword))

RuntimeError: The expanded size of the tensor (400) must match the existing size (150) at non-singleton dimension 1.  Target sizes: [950, 400].  Tensor sizes: [950, 150]

**Comment by vzhong** [comment]
Hi @Adnandev123 this code is set up to use GloVe (300) w/ Character ngram (100) embeddings (e.g. total is 400). If you change it to 50-dim embeddings you need to pass in `demb=150`.
