### ISSUE TITLE
Connection error when preprocessing.

### ISSUE THREAD

**Issue by alexlfyang** [salesforce/glad#11]
Same issue with https://github.com/stanfordnlp/stanza/issues/16. Any solution?

**Comment by vzhong** [comment]
Hi @narukamiko are you seeing this with the dockerized version?

**Comment by vzhong** [comment]
I wasn't able to produce this with the dockerized version. I think the version of stanza we use should have already incorporated the timeout fix. In any event, you can wrap the CoreNLP call in `dataset.py` with another retry look such as in https://github.com/stanfordnlp/stanza/pull/18/commits/859f67e8301a6cb6509bb59e2ca0f04885c493f9 and see if that helps?

**Comment by alexlfyang** [comment]
@vzhong Thanks for your advice. But it does not work yet. Could you please share the `data/woz` folder including annotation? I'm not running dockerized version.
