### ISSUE TITLE
The model do not predict system_transcript?

### ISSUE THREAD

**Issue by guotong1988** [salesforce/glad#12]
![image](https://user-images.githubusercontent.com/4702353/64498038-0d0fe500-d2e5-11e9-8ec8-62911c680ed2.png)
@vzhong Thank you!

**Comment by vzhong** [comment]
Hi yes this model is for state tracking, not response generation.

**Comment by akashicMarga** [comment]
@vzhong  @guotong1988  Apart from slot value pairs does the model predict the next action that should be taken by the system?

**Comment by vzhong** [comment]
No this model is a state tracker. It is not a dialogue policy.
