### ISSUE TITLE
How does the context info flow?

### ISSUE THREAD

**Issue by guotong1988** [salesforce/glad#13]
![image](https://user-images.githubusercontent.com/4702353/67443997-c2022500-f639-11e9-8897-ad204efbd38f.png)

It seems that one batch contains batch_size of one-turn-utterance.
@vzhong Thank you!!

**Comment by vzhong** [comment]
sorry I don't understand the question here

**Comment by guotong1988** [comment]
Thank you for your reply. 
I guess the model should process multi-turn for one time.

我感觉模型应该能一次输入 几个turn一起

**Comment by guotong1988** [comment]
我debug看batch里有50个Turn，每个Turn只有一个utterance

**Comment by guotong1988** [comment]
我猜模型是不是可以把前几个Turn的历史信息告诉当前的Turn，
这在GLAD是怎么做到的

**Comment by vzhong** [comment]
Hi, this is not a bug. The GLAD tracker does not carry over turn-to-turn context apart from the previous system action. For a model that does do that, please see follow-up work such as http://faculty.cse.tamu.edu/huangrh/papers/naacl19_Dialog_State_Tracking.pdf.

**Comment by guotong1988** [comment]
Thank you very much!
