### ISSUE TITLE
Error when run preprocess_data.py

### ISSUE THREAD

**Issue by PhungVanDuy** [salesforce/glad#5]
![Screenshot from 2019-03-22 12-54-36](https://user-images.githubusercontent.com/28798474/54803346-bd3f5200-4ca1-11e9-8fb0-f755a1e30ea7.png)

**Comment by ashleyyy94** [comment]
Same issue here. Connection refused.

**Comment by vzhong** [comment]
Is the Stanford NLP server running?

```
docker run --name corenlp -d -p 9000:9000 vzhong/corenlp-server
```

**Comment by ashleyyy94** [comment]
ah no it wasn't. But I thought we did not have to use docker to preprocess the data

**Comment by vzhong** [comment]
Sorry about the ambiguity in the instructions - you still need to run the CoreNLP server regardless of whether you use Docker for training/evaluation. I've updated the README accordingly to reflect this.
