### ISSUE TITLE
Reproducing DSTC-2 evaluation results

### ISSUE THREAD

**Issue by kolk** [salesforce/glad#8]
I have downloaded the clean dstc-2 dataset and trained the system but unable to reproduce the results. Please share the hyper-parameters for the dstc-2 dataset.

**Comment by kolk** [comment]
I have achieved 64% joint_goal accuracy on the test set and and 70% on dev set on clean DSTC2 dataset. How do I achieve the reported results?

**Comment by SkyAndCloud** [comment]
Hi, I'm currently work on clean version DSTC2 dataset. But I encoutered problem when I exec `preprocess_data.py`, here is the traceback:

```
Traceback (most recent call last):
File "preprocess_dstc2.py", line 52, in <module>
dataset[s] = Dataset.annotate_raw(os.path.join(draw, fname))
File "/home/user/glad/dataset.py", line 110, in annotate_raw
return cls([Dialogue.annotate_raw(d) for d in tqdm(data)])
File "/home/user/glad/dataset.py", line 110, in <listcomp>
return cls([Dialogue.annotate_raw(d) for d in tqdm(data)])
File "/home/user/glad/dataset.py", line 83, in annotate_raw
return cls(raw['dialogue_idx'], [Turn.annotate_raw(t) for t in raw['dialogue']])
File "/home/user/glad/dataset.py", line 83, in <listcomp>
return cls(raw['dialogue_idx'], [Turn.annotate_raw(t) for t in raw['dialogue']])
File "/home/user/glad/dataset.py", line 56, in annotate_raw
belief_state=raw['belief_state'],
KeyError: 'belief_state'
```

It seems that DSTC2 dataset doesn't have a field "belief_state" in json, but WOZ has this filed. I want to remove all code about "belief_state" in dataset.py (like https://github.com/salesforce/glad/blob/ccd1f0cf244d0758bd0284c055050bad4a8d1ec6/dataset.py#L28) but I find that it is used to calculate predictions on evaluation mode (https://github.com/salesforce/glad/blob/ccd1f0cf244d0758bd0284c055050bad4a8d1ec6/dataset.py#L152). I feel confused. How can I do this correctly? Please help me, thanks a lot!

**Comment by kolk** [comment]
Hello, the belief state field do not exist explicitly in DSTC2. You can track the belief state by accumulating the turn labels for a dialogue.

```
 for d in self.dialogues:
            pred_state = {}
            gold_state = {}
            for t in d.turns:
                gold_request = set([(s, v) for s, v in t.turn_label if s == 'request'])
                gold_inform = set([(s, v) for s, v in t.turn_label if s != 'request'])
                pred_request = set([(s, v) for s, v in preds[i] if s == 'request'])
                pred_inform = set([(s, v) for s, v in preds[i] if s != 'request'])
                request.append(gold_request == pred_request)
                inform.append(gold_inform == pred_inform)
                gold_recovered = set()
                pred_recovered = set()
                for s, v in pred_inform:
                    pred_state[s] = v      
                for s, v in gold_inform:
                    gold_state[s] = v
                for s, v in pred_state.items():
                    pred_recovered.add(('inform', s, v))
                for s, v in gold_state.items():
                    gold_recovered.add(('inform', s, v))
                joint_goal.append(gold_recovered == pred_recovered)  
```

**Comment by SkyAndCloud** [comment]
Thank you for the quick reply. I'm new to this dataset and I don't know where to insert your code. Can you provide related file in gist and your correct preprocess steps? Thank you a lot!

**Comment by vzhong** [comment]
Hi guys,

Unfortunately it's unlikely that this will happen, since I no longer have access to the experiments. With regards to the numbers you are seeing, from a first inspection the code snippet by @kolk seems correct to me. Are you also using word dropout as mentioned in the paper? This is crucial to attaining the performance we got for DSTC2.
