### ISSUE TITLE
Wrong dimension size for the local self-attention component?

### ISSUE THREAD

**Issue by laituan245** [salesforce/glad#9]
Hi.

Since the local RNN for a slot type is a bidirectional RNN, should the local self-attention component be initialized as 

> SelfAttention(2 * dhid, dropout=self.dropout.get('selfattn', 0.)) 

instead of 

> SelfAttention(din, dropout=self.dropout.get('selfattn', 0.))

as in the [line 101 of glad.py](https://github.com/salesforce/glad/blob/master/models/glad.py#L101)?

**Comment by vzhong** [comment]
You are right! sorry about that!

**Comment by vzhong** [comment]
fixed with cc3217437128578a1942582670104bc214506a5e. Thanks again!
